# tasks file for create-workers
---
- name: Create Worker 1
  ec2:
    key_name: "{{ key_name }}" # This is now the dynamically created key
    instance_type: t2.micro
    image: "{{ ami_id }}"  ##Need to add a Ubuntu or CentOS image
    wait: yes
    count: 1
    vpc_subnet_id: "{{ vpc_subnet_id }}"  ##Could use default vpc or create a new vpc
    assign_public_ip: yes
    region: "{{ aws_region }}"
    instance_tags:
       Name: Worker 1

- name: Create Worker 2
  ec2:
    key_name: "{{ key_name }}" # This is now the dynamically created key
    instance_type: t2.micro
    image: "{{ ami_id }}"  ##Need to add a Ubuntu or CentOS image
    wait: yes
    count: 1
    vpc_subnet_id: "{{ vpc_subnet_id }}"  ##Could use default vpc or create a new vpc
    assign_public_ip: yes
    region: "{{ aws_region }}"
    instance_tags:
       Name: Worker 2
