---
- name: Generate a random string for s3 bucket
  set_fact:
    r: "{{ 100 | random }}"

- name: Create s3 bucket
  s3_bucket:
    name: "akashbalanis3bucket-{{ r }}" 
    region: "us-east-1"
    versioning: yes
    aws_access_key: "{{ lookup('env','aws_access_key') }}"
    aws_secret_key: "{{ lookup('env','aws_secret_key') }}"
  register: s3_url

- name: Set s3 name as fact
  set_fact: 
    s3Name: "{{ s3_url['name'] }}"

- name: Display s3 url
  debug: var=s3_url